# Generated by Django 3.2.18 on 2023-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link_git',
            field=models.CharField(default='', max_length=200),
        ),
    ]
